

#ifndef NESS_MKV_DEFS_H
#define NESS_MKV_DEFS_H


#define EBML_ID_HEADER                  0x1A45DFA3
#define EBML_ID_EBMLVERSION             0x4286
#define EBML_ID_EBMLREADVERSION         0x42F7
#define EBML_ID_EBMLMAXIDLENGTH         0x42F2
#define EBML_ID_EBMLMAXSIZELENGTH       0x42F3
#define EBML_ID_DOCTYPE                 0x4282
#define EBML_ID_DOCTYPEVERSION          0x4287
#define EBML_ID_DOCTYPEREADVERSION      0x4285
#define EBML_ID_VOID                    0xEC


#define MATROSKA_ID_SEGMENT             0x18538067


#define MATROSKA_ID_SEEKHEAD            0x114D9B74
#define MATROSKA_ID_SEEKENTRY           0x4DBB
#define MATROSKA_ID_SEEKID              0x53AB
#define MATROSKA_ID_SEEKPOSITION        0x53AC


#define MATROSKA_ID_INFO                0x1549A966
#define MATROSKA_ID_TIMESTAMPSCALE      0x2AD7B1
#define MATROSKA_ID_DURATION            0x4489
#define MATROSKA_ID_MUXINGAPP           0x4D80
#define MATROSKA_ID_WRITINGAPP          0x5741


#define MATROSKA_ID_TRACKS              0x1654AE6B
#define MATROSKA_ID_TRACKENTRY          0xAE
#define MATROSKA_ID_TRACKNUMBER         0xD7
#define MATROSKA_ID_TRACKUID            0x73C5
#define MATROSKA_ID_TRACKTYPE           0x83
#define MATROSKA_ID_TRACKAUDIO          0xE1
#define MATROSKA_ID_TRACKVIDEO          0xE0
#define MATROSKA_ID_CODECID             0x86
#define MATROSKA_ID_CODECPRIVATE        0x63A2
#define MATROSKA_ID_FLAGLACING          0x9C
#define MATROSKA_ID_TRACKDEFAULTDURATION 0x23E383


#define MATROSKA_ID_VIDEOPIXELWIDTH     0xB0
#define MATROSKA_ID_VIDEOPIXELHEIGHT    0xBA
#define MATROSKA_ID_VIDEODISPLAYWIDTH   0x54B0
#define MATROSKA_ID_VIDEODISPLAYHEIGHT  0x54BA


#define MATROSKA_ID_CLUSTER             0x1F43B675
#define MATROSKA_ID_CLUSTERTIMESTAMP    0xE7
#define MATROSKA_ID_SIMPLEBLOCK         0xA3


#define MATROSKA_ID_CUES                0x1C53BB6B
#define MATROSKA_ID_CUEPOINT            0xBB
#define MATROSKA_ID_CUETIME             0xB3
#define MATROSKA_ID_CUETRACKPOSITIONS   0xB7
#define MATROSKA_ID_CUETRACK            0xF7
#define MATROSKA_ID_CUECLUSTERPOSITION  0xF1


#define MATROSKA_TRACK_TYPE_VIDEO       1
#define MATROSKA_TRACK_TYPE_AUDIO       2

#endif
